version: "3.7"

networks:
  fixed_compose_network:
    ipam:
      driver: default
      config:
        - subnet: 172.24.1.0/24

services:
  jupyter_pytorch:
    build: "./jupyter_pytorch/"
    image: "img_jupyter_pytorch"
    container_name: "jupyter_pytorch"
    ports:
      - 8888:8888
    expose:
      - "8888"
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    volumes:
      - ./jupyter_pytorch/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    user: 0:0
    stdin_open: true
    networks:
      fixed_compose_network:
        ipv4_address: 172.24.1.2
